apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cloud-run-pipeline
description: Deploy to Cloud Run using Cloud Deploy
serialPipeline:
  stages:
    - targetId: dev
      profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Cloud Run deployment target
run:
  location: projects/faa-gcp-training-14-kfa-0808/locations/us-central1

