steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/faa-gcp-training-14-kfa-0808/cloud-run-app:$SHORT_SHA',
        '.'
      ]

  # Step 2: Push the image to Container Registry / Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'gcr.io/faa-gcp-training-14-kfa-0808/cloud-run-app:$SHORT_SHA']

  # Step 3: Trigger Cloud Deploy to roll out the new release
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'deploy',
        'releases',
        'create',
        'release-$SHORT_SHA',
        '--delivery-pipeline=cloud-run-pipeline',
        '--region=us-central1',
        '--images=cloud-run-app=gcr.io/faa-gcp-training-14-kfa-0808/cloud-run-app:$SHORT_SHA'
      ]

# Optional: define substitutions
substitutions:
  _REGION: us-central1
  _SERVICE_NAME: cloud-ru
