steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/faa-gcp-training-14-kfa-0808/my-repo/cloud-run-app:$SHORT_SHA',
        '.'
      ]

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'us-central1-docker.pkg.dev/faa-gcp-training-14-kfa-0808/my-repo/cloud-run-app:$SHORT_SHA']

  # Step 3: Trigger Cloud Deploy to roll out the new release
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'deploy',
        'releases',
        'create',
        'release-$SHORT_SHA',
        '--delivery-pipeline=cloud-run-pipeline',
        '--region=us-central1',
        '--images=cloud-run-app=us-central1-docker.pkg.dev/faa-gcp-training-14-kfa-0808/my-repo/cloud-run-app:$SHORT_SHA'
      ]

# Optional: define substitutions
substitutions:
  _REGION: us-central1
  _SERVICE_NAME: cloud-run-app

# Optional: timeout for the whole build
timeout: '900s'

# ✅ Disable GCS logs bucket
options:
  logging: CLOUD_LOGGING_ONLY

