apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: cloud-run-app
build:
  artifacts:
    - image: gcr.io/faa-gcp-training-14-kfa-0808/cloud-run-app
deploy:
  cloudrun:
    projectId: faa-gcp-training-14-kfa-0808
    region: us-central1
    serviceName: cloud-run-app

